/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nx7inTTpF3l
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"

export function loginform() {
  return (
    (<div
      className="flex items-center justify-center h-screen bg-background dark:bg-[#1a1b1e]">
      <div
        className="bg-card dark:bg-[#1f2023] rounded-2xl shadow-xl p-8 w-full max-w-md">
        <h1
          className="text-3xl font-bold text-center text-card-foreground dark:text-[#f1f1f1] mb-6">Login</h1>
        <div className="space-y-4">
          <div>
            <Label htmlFor="email" className="text-muted-foreground dark:text-[#b3b3b3]">
              Email
            </Label>
            <Input
              id="email"
              type="email"
              placeholder="Enter your email"
              className="bg-input dark:bg-[#2c2d31] text-card-foreground dark:text-[#f1f1f1] border-none focus:ring-0 focus:border-none" />
          </div>
          <div>
            <Label htmlFor="password" className="text-muted-foreground dark:text-[#b3b3b3]">
              Password
            </Label>
            <Input
              id="password"
              type="password"
              placeholder="Enter your password"
              className="bg-input dark:bg-[#2c2d31] text-card-foreground dark:text-[#f1f1f1] border-none focus:ring-0 focus:border-none" />
          </div>
          <Button
            className="w-full bg-primary dark:bg-[#0077b6] text-primary-foreground dark:text-[#f1f1f1] hover:bg-primary/90 dark:hover:bg-[#005a8d] transition-colors">
            Login
          </Button>
          <div className="flex items-center justify-between">
            <Separator className="w-full" />
            <span className="mx-4 text-muted-foreground dark:text-[#b3b3b3]">or</span>
            <Separator className="w-full" />
          </div>
          <div className="grid grid-cols-3 gap-4">
            <Button
              variant="outline"
              className="text-card-foreground dark:text-[#f1f1f1] hover:bg-muted dark:hover:bg-[#2c2d31] transition-colors">
              <GithubIcon className="h-5 w-5" />
            </Button>
            <Button
              variant="outline"
              className="text-card-foreground dark:text-[#f1f1f1] hover:bg-muted dark:hover:bg-[#2c2d31] transition-colors">
              <FacebookIcon className="h-5 w-5" />
            </Button>
            <Button
              variant="outline"
              className="text-card-foreground dark:text-[#f1f1f1] hover:bg-muted dark:hover:bg-[#2c2d31] transition-colors">
              <ChromeIcon className="h-5 w-5" />
            </Button>
          </div>
        </div>
      </div>
    </div>)
  );
}

function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function GithubIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>)
  );
}
